baseURL = '/'
languageCode = 'en-us'
title = 'PenumbraOS'

[params]
  description = 'A developer-friendly resurrection of the Humane Ai Pin'
  tagline = 'Make your Ai Pin usable again'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  section_group = 'section_groups'
  tag = 'tags'

[params.footer]
  note = 'PenubmraOS is not affiliated with Humane Inc. or HP Inc. The Ai Pin trademark and archived content remains property of HP.'
  [[params.footer.links]]
    name = 'GitHub'
    url = 'https://github.com/penumbraOS/'
  [[params.footer.links]]
    name = 'Blog'
    url = 'https://writings.agg.im/'

[menu]
  [[menu.main]]
    identifier = 'getting-started'
    name = 'Getting Started'
    url = '/getting-started/'
    weight = 10
  [[menu.main]]
    identifier = 'guide'
    name = 'Guide'
    url = '/guide/'
    weight = 20
  [[menu.main]]
    identifier = 'device'
    name = 'Device'
    url = '/device/'
    weight = 30
  [[menu.main]]
    identifier = 'archive'
    name = 'Archive'
    url = '/archive/'
    weight = 40
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 50
